### ISSUE TITLE
Raku 6.d zef install  fails with "Cannot assign to an immutable value"

### ISSUE THREAD

**Issue by eiselekd** [raku-community-modules/MoarVM-Remote#2]
custom compile/install of raku:
$perl6 --version
This is Rakudo version 2020.02.1-408-g1a536ca9d built on MoarVM version 2020.02.1-163-g8b1
implementing Raku 6.d.
$zef --version
v0.8.4

$ zef install --force-install MoarVM::Remote
===> Searching for: MoarVM::Remote
===> Testing: MoarVM::Remote:ver<0.0.1>
[MoarVM::Remote]     # let's go!
[MoarVM::Remote] STDERR: # looking for data
[MoarVM::Remote]     # looking to suspend a thread
[MoarVM::Remote]     # suspended, yay
[MoarVM::Remote] STDERR: marking thread 1 unblocked, but its status is already NONE.
[MoarVM::Remote] STDERR: # got data
[MoarVM::Remote]     # positional or seq
[MoarVM::Remote] A react block:
[MoarVM::Remote]   in sub run_debugtarget at /home/eiselekd/.zef/store/p6-moarvm-remote.git/b9e802f746648e9558686096a44ef72d2fe9abd3/t/lib/MoarRemoteTest.pm6 (MoarRemoteTest) line 31
[MoarVM::Remote]   in sub run_testplan at /home/eiselekd/.zef/store/p6-moarvm-remote.git/b9e802f746648e9558686096a44ef72d2fe9abd3/t/lib/MoarRemoteTest.pm6 (MoarRemoteTest) line 162
[MoarVM::Remote]   in block <unit> at t/05-suspend-resume.t line 18
[MoarVM::Remote] Died because of the exception:
[MoarVM::Remote]     Cannot assign to an immutable value
[MoarVM::Remote]       in block  at /home/eiselekd/.zef/store/p6-moarvm-remote.git/b9e802f746648e9558686096a44ef72d2fe9abd3/t/lib/MoarRemoteTest.pm6 (MoarRemoteTest) line 187
[MoarVM::Remote]       in block  at /home/eiselekd/.zef/store/p6-moarvm-remote.git/b9e802f746648e9558686096a44ef72d2fe9abd3/t/lib/MoarRemoteTest.pm6 (MoarRemoteTest) line 178
[MoarVM::Remote]       in block  at /home/eiselekd/.zef/store/p6-moarvm-remote.git/b9e802f746648e9558686096a44ef72d2fe9abd3/t/lib/MoarRemoteTest.pm6 (MoarRemoteTest) line 61
===> Testing [FAIL]: MoarVM::Remote:ver<0.0.1>
Aborting due to test failure: MoarVM::Remote:ver<0.0.1> (use --force-test to override)

**Comment by eiselekd** [comment]
Created https://github.com/edumentab/p6-moarvm-remote/pull/3

**Comment by lizmat** [comment]
I think this issue is now fixed.
